# Generated by Django 5.0 on 2023-12-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=8, null=True),
        ),
    ]
