# Generated by Django 5.0 on 2023-12-11 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_cart', '0002_usercart_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercart',
            name='price',
        ),
    ]
