# Generated by Django 5.0 on 2023-12-12 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cartNumber',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='cvv',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='expirationDate',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
