# Generated by Django 4.2.7 on 2023-12-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paymentMethod',
            field=models.CharField(max_length=17, null=True),
        ),
    ]
