# Generated by Django 5.0 on 2023-12-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_payment_paymentmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paymentMethod',
            field=models.CharField(choices=[('mastercard', 'Mastercard'), ('visa', 'Visa'), ('amex', 'American Express')], max_length=17, null=True),
        ),
    ]
