# Generated by Django 5.0 on 2023-12-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_payment_paymentmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expirationDate',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
